package com.example.furniturecloudy.util

import android.util.Log
import com.example.furniturecloudy.data.Product
import com.google.firebase.firestore.FirebaseFirestore
import kotlinx.coroutines.tasks.await
import kotlin.random.Random

/**
 * Manager để insert và delete fake data trên Firebase
 *
 * 🎯 CÁCH DÙNG:
 * 1. Gọi insertFakeProducts() để insert 1000-5000 fake products
 * 2. Sau khi xong môn học, gọi deleteAllFakeProducts() để xóa sạch
 *
 * ⚠️ CHÚ Ý:
 * - Fake products có field `isFakeData = true` để phân biệt với real data
 * - KHÔNG XÓA products có isFakeData = false (hoặc không có field này)
 */
object FirebaseFakeDataManager {

    private const val TAG = "FakeDataManager"
    private const val COLLECTION_PRODUCTS = "Products"

    // Categories thật từ app
    private val categories = listOf(
        "Chair",
        "Table",
        "Cupboard",
        "Accessory",
        "Furniture"
    )

    private val adjectives = listOf(
        "Modern",
        "Classic",
        "Vintage",
        "Luxury",
        "Minimalist",
        "Rustic",
        "Contemporary",
        "Traditional",
        "Industrial",
        "Scandinavian",
        "Elegant",
        "Stylish"
    )

    private val materials = listOf(
        "Wood",
        "Metal",
        "Glass",
        "Leather",
        "Fabric",
        "Plastic",
        "Bamboo",
        "Rattan"
    )

    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    // INSERT FAKE DATA
    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

    /**
     * Insert fake products lên Firebase
     *
     * @param count Số lượng products cần insert (default: 1000)
     * @param batchSize Số lượng products mỗi batch (max 500 do giới hạn Firestore)
     * @return Số lượng products đã insert thành công
     */
    suspend fun insertFakeProducts(
        firestore: FirebaseFirestore,
        count: Int = 1000,
        batchSize: Int = 100
    ): Result<Int> {
        return try {
            Log.d(TAG, "🚀 Starting to insert $count fake products...")

            var totalInserted = 0
            val batches = (count + batchSize - 1) / batchSize  // Ceiling division

            for (batchIndex in 0 until batches) {
                val startIndex = batchIndex * batchSize
                val endIndex = minOf((batchIndex + 1) * batchSize, count)
                val currentBatchSize = endIndex - startIndex

                Log.d(TAG, "📦 Batch ${batchIndex + 1}/$batches: Inserting $currentBatchSize products...")

                // Tạo batch write
                val batch = firestore.batch()

                for (i in startIndex until endIndex) {
                    val fakeProduct = generateFakeProduct(i)

                    // Tạo document với auto-generated ID
                    val docRef = firestore.collection(COLLECTION_PRODUCTS).document()

                    // Convert Product to Map và thêm field isFakeData
                    val productMap = productToMap(fakeProduct).toMutableMap()
                    productMap["isFakeData"] = true  // ⚠️ QUAN TRỌNG: Đánh dấu fake data

                    batch.set(docRef, productMap)
                }

                // Commit batch
                batch.commit().await()
                totalInserted += currentBatchSize

                Log.d(TAG, "✅ Batch ${batchIndex + 1} completed. Total: $totalInserted/$count")
            }

            Log.d(TAG, "🎉 Successfully inserted $totalInserted fake products!")
            Result.success(totalInserted)

        } catch (e: Exception) {
            Log.e(TAG, "❌ Error inserting fake products", e)
            Result.failure(e)
        }
    }

    /**
     * Generate 1 fake product
     */
    private fun generateFakeProduct(index: Int): Product {
        val category = categories[index % categories.size]
        val adjective = adjectives[Random.nextInt(adjectives.size)]
        val material = materials[Random.nextInt(materials.size)]

        return Product(
            id = "",  // Auto-generated by Firestore
            name = "$adjective $material $category",
            price = (50 + Random.nextInt(450)).toFloat(),  // $50 - $500
            category = category,
            stock = Random.nextInt(100),  // 0-99
            averageRating = 3.0f + Random.nextInt(20) / 10f,  // 3.0-5.0
            offerPercentage = if (Random.nextInt(3) == 0) {
                0.05f + Random.nextInt(30) / 100f  // 5%-35% off
            } else {
                null
            },
            images = listOf(
                "https://picsum.photos/seed/${index}/400/400",
                "https://picsum.photos/seed/${index + 10000}/400/400"
            )
        )
    }

    /**
     * Convert Product to Map for Firestore
     */
    private fun productToMap(product: Product): Map<String, Any?> {
        return mapOf(
            "name" to product.name,
            "price" to product.price,
            "category" to product.category,
            "stock" to product.stock,
            "averageRating" to product.averageRating,
            "offerPercentage" to product.offerPercentage,
            "images" to product.images
        )
    }

    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    // DELETE FAKE DATA
    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

    /**
     * Xóa TẤT CẢ fake products từ Firebase
     *
     * ⚠️ CHÚ Ý: CHỈ xóa products có isFakeData = true
     *
     * @return Số lượng products đã xóa
     */
    suspend fun deleteAllFakeProducts(firestore: FirebaseFirestore): Result<Int> {
        return try {
            Log.d(TAG, "🗑️ Starting to delete fake products...")

            // Query tất cả fake products
            val snapshot = firestore.collection(COLLECTION_PRODUCTS)
                .whereEqualTo("isFakeData", true)
                .get()
                .await()

            if (snapshot.isEmpty) {
                Log.d(TAG, "ℹ️ No fake products found")
                return Result.success(0)
            }

            val totalCount = snapshot.size()
            Log.d(TAG, "📋 Found $totalCount fake products. Deleting...")

            var deletedCount = 0
            val batchSize = 500  // Firestore batch limit

            // Delete theo batch
            val batches = (totalCount + batchSize - 1) / batchSize
            val documents = snapshot.documents

            for (batchIndex in 0 until batches) {
                val startIndex = batchIndex * batchSize
                val endIndex = minOf((batchIndex + 1) * batchSize, totalCount)

                val batch = firestore.batch()

                for (i in startIndex until endIndex) {
                    batch.delete(documents[i].reference)
                }

                batch.commit().await()
                deletedCount += (endIndex - startIndex)

                Log.d(TAG, "✅ Batch ${batchIndex + 1}/$batches deleted. Total: $deletedCount/$totalCount")
            }

            Log.d(TAG, "🎉 Successfully deleted $deletedCount fake products!")
            Result.success(deletedCount)

        } catch (e: Exception) {
            Log.e(TAG, "❌ Error deleting fake products", e)
            Result.failure(e)
        }
    }

    /**
     * Count số lượng fake products hiện tại
     */
    suspend fun countFakeProducts(firestore: FirebaseFirestore): Result<Int> {
        return try {
            val snapshot = firestore.collection(COLLECTION_PRODUCTS)
                .whereEqualTo("isFakeData", true)
                .get()
                .await()

            Result.success(snapshot.size())
        } catch (e: Exception) {
            Log.e(TAG, "❌ Error counting fake products", e)
            Result.failure(e)
        }
    }

    /**
     * Count tổng số products (bao gồm cả real và fake)
     */
    suspend fun countAllProducts(firestore: FirebaseFirestore): Result<Int> {
        return try {
            val snapshot = firestore.collection(COLLECTION_PRODUCTS)
                .get()
                .await()

            Result.success(snapshot.size())
        } catch (e: Exception) {
            Log.e(TAG, "❌ Error counting all products", e)
            Result.failure(e)
        }
    }
}